# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Reflective Praxis
tagline:             'Thoughts on engineering and software development'
description:         'A collection of thoughts, reflections, and ideas about engineering in general and software development in particular.'
url:                 http://allanmcinnes.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allan McInnes
  url:               http://allanmcinnes.github.io
  email:             allan.mcinnes@acm.org

# Custom vars
version:             1.0.0
